name: Frontend Ship

on:
    workflow_run:
        workflows: ["Code Quality"]
        types:
            - completed
        branches: [main]

jobs:
    deploy-notifications:
        runs-on: ubuntu-latest
        if: github.event.workflow_run.conclusion != 'cancelled'

        steps:
            - name: Check Quality Workflow Success
              id: quality_check
              run: |
                  if [ "${{ github.event.workflow_run.conclusion }}" == "success" ]; then
                    echo "quality_passed=true" >> $GITHUB_OUTPUT
                  else
                    echo "quality_passed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Slack Notification - Ship Success
              if: steps.quality_check.outputs.quality_passed == 'true'
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                        "text": "Frontend Ship Success - ${{ github.event.workflow_run.head_commit.author.name }}"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

            - name: Slack Notification - Ship Failure
              if: steps.quality_check.outputs.quality_passed == 'false'
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                        "text": "Frontend Ship Failed - ${{ github.event.workflow_run.head_commit.author.name }}"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
