name: Frontend Ship

on:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    deploy-notifications:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Get current time (Europe/Paris)
              id: current-time
              run: echo "TIME=$(TZ='Europe/Paris' date +'%d/%m/%Y at %H:%M')" >> $GITHUB_OUTPUT

            - name: Get short SHA
              id: short-sha
              run: echo "SHORT_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Detect design system changes
              id: design-changes
              run: |
                  if git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep -E "(src/components|\.storybook)" > /dev/null; then
                      echo "changed=true" >> $GITHUB_OUTPUT

                      component_names=$(git diff --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }} | grep 'src/components' | cut -d'/' -f4 | sort | uniq | head -5)

                      if [ -n "$component_names" ]; then
                          components=$(echo "$component_names" | sed 's/^/`/' | sed 's/$/`/' | tr '\n' ' / ' | sed 's/ \/ $//')
                      else
                          # Si seulement .storybook modifié
                          components="`Storybook config`"
                      fi

                      echo "changed_components=$components" >> $GITHUB_OUTPUT
                  else
                      echo "changed=false" >> $GITHUB_OUTPUT
                  fi

            - name: Slack Notification - Ship Success
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  payload: |
                      {
                          "blocks": [
                              {
                                  "type": "header",
                                  "text": {
                                      "type": "plain_text",
                                      "text": "Production-ready updates added to main"
                                  }
                              },
                              {
                                  "type": "context",
                                  "elements": [
                                      {
                                          "text": "*Merged* ${{ steps.current-time.outputs.TIME }} / *Quality checks completed*",
                                          "type": "mrkdwn"
                                      }
                                  ]
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*Details*"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`Author`*     ${{ github.event.pull_request.user.login }}"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`PR`*            ${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`Changes`*   +${{ github.event.pull_request.additions }} -${{ github.event.pull_request.deletions }} (${{ github.event.pull_request.changed_files }} files)"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`Commit`*     <${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}|${{ steps.short-sha.outputs.SHORT_SHA }}>"
                                  }
                              },
                              {
                                  "type": "divider"
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*Status*"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`Impact`*    ${{ github.event.pull_request.additions > 200 && 'Large' || github.event.pull_request.additions < 50 && 'Small' || 'Medium' }} changes"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "*`Status`*    Ready for staging deployment"
                                  }
                              },
                              {
                                  "type": "section",
                                  "text": {
                                      "type": "mrkdwn",
                                      "text": "By clicking <${{ github.event.pull_request.html_url }}|*here*>, you will be able to have a detailed view about the merged pull request."
                                  }
                              }
                          ]
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

            - name: Slack Notification - Design system updates
              if: steps.design-changes.outputs.changed == 'true'
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  channel-id: ${{ secrets.SLACK_DESIGN_SYSTEM_CHANNEL_ID }}
                  payload: |
                      {
                      	"blocks": [
                      		{
                      			"type": "header",
                      			"text": {
                      				"type": "plain_text",
                      				"text": "Design System Updated"
                      			}
                      		},
                      		{
                      			"type": "section",
                      			"text": {
                      				"type": "mrkdwn",
                      				"text": "${{ github.event.pull_request.title }} (#${{ github.event.pull_request.number }})"
                      			}
                      		},
                      		{
                      			"type": "divider"
                      		},
                      		{
                      			"type": "section",
                      			"text": {
                      				"type": "mrkdwn",
                      				"text": "*Details*"
                      			}
                      		},
                      		{
                      			"type": "section",
                      			"text": {
                      				"type": "mrkdwn",
                      				"text": "Component updated: ${{ steps.design-changes.outputs.changed_components }}"
                      			}
                      		},
                      		{
                      			"type": "section",
                      			"text": {
                      				"type": "mrkdwn",
                      				"text": "View the updated <https://6855a5efeaea3708446ecdca-jlnygxvtlx.chromatic.com|*Storybook*> or check the <https://www.chromatic.com/builds?appId=6855a5efeaea3708446ecdca|*latest build*> in Chromatic."
                      			}
                      		}
                      	]
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
