name: Frontend Ship

on:
    pull_request:
        types: [closed]
        branches: [main]

jobs:
    deploy-notifications:
        runs-on: ubuntu-latest
        if: github.event.pull_request.merged == true

        steps:
            - name: Get current time (Europe/Paris)
              id: current-time
              run: echo "TIME=$(TZ='Europe/Paris' date +'%d/%m/%Y at %H:%M')" >> $GITHUB_OUTPUT

            - name: Get short SHA
              id: short-sha
              run: echo "SHORT_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT

            - name: Slack Notification - Ship Success
              uses: slackapi/slack-github-action@v1.24.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  unfurl-links: false
                  unfurl-media: false
                  payload: |
                      {
                        "blocks": [
                          {
                            "type": "header",
                            "text": {
                              "type": "plain_text",
                              "text": "Production-ready updates added to main"
                            }
                          },
                          {
                            "type": "context",
                            "elements": [
                              {
                                "text": "*Merged* ${{ steps.current-time.outputs.TIME }} / *Quality checks completed*",
                                "type": "mrkdwn"
                              }
                            ]
                          },
                          {
                            "type": "divider"
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*Details*"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`Author`*     ${{ github.event.pull_request.user.login }}"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`PR`*           ${{ github.event.pull_request.title }} ${{ github.event.pull_request.number }}"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`Changes`*   +${{ github.event.pull_request.additions }} -${{ github.event.pull_request.deletions }} (${{ github.event.pull_request.changed_files }} files)"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`Commit`*    <${{ github.event.pull_request.html_url }}/commits/${{ github.event.pull_request.head.sha }}|${{ steps.short-sha.outputs.SHORT_SHA }}>"
                            }
                          },
                          {
                            "type": "divider"
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*Status*"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`Impact`*    ${{ github.event.pull_request.additions > 200 && 'Large' || github.event.pull_request.additions < 50 && 'Small' || 'Medium' }} changes"
                            }
                          },
                          {
                            "type": "section",
                            "text": {
                              "type": "mrkdwn",
                              "text": "*`Status`*    Ready for staging deployment"
                            }
                          },
                          {
                              "type": "actions",
                              "elements": [
                                  {
                                      "type": "button",
                                      "text": {"type": "plain_text", "text": "View PR #${{ github.event.pull_request.number }}"},
                                      "url": "${{ github.event.pull_request.html_url }}"
                                  }
                              ]
                          }
                        ]
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
